OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2013 --category news-releases > debug-2013.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2014 --category news-releases > debug-2014.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2015 --category news-releases > debug-2015.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2016 --category news-releases > debug-2016.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2017 --category news-releases > debug-2017.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2018 --category news-releases > debug-2018.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2019 --category news-releases > debug-2019.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2013 --category speeches --follow-related-links False > debug-speeches-2013.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2014 --category speeches --follow-related-links False > debug-speeches-2014.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2015 --category speeches --follow-related-links False > debug-speeches-2015.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2016 --category speeches --follow-related-links False > debug-speeches-2016.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2017 --category speeches --follow-related-links False > debug-speeches-2017.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2018 --category speeches --follow-related-links False > debug-speeches-2018.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2019 --category speeches --follow-related-links False > debug-speeches-2019.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2013 --category others --follow-related-links False > debug-others-2013.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2014 --category others --follow-related-links False > debug-others-2014.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2015 --category others --follow-related-links False > debug-others-2015.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2016 --category others --follow-related-links False > debug-others-2016.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2017 --category others --follow-related-links False > debug-others-2017.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2018 --category others --follow-related-links False > debug-others-2018.txt 2>&1 &&
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 nas.py --year 2019 --category others --follow-related-links False > debug-others-2019.txt 2>&1
